export default {
  SET_CHARTS: 'SET_CHARTS',
  ADD_LAYER: 'ADD_LAYER',
  REMOVE_LAYER: 'REMOVE_LAYER',
  ADD_CRUMB: 'ADD_CRUMB',
  REMOVE_CRUMB: 'REMOVE_CRUMB',
  SET_PROP: 'SET_PROP',
  SELECT_LAYER: 'SELECT_LAYER',
  TOGGLE_HIDDEN: 'TOGGLE_HIDDEN',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL'
};
